### ISSUE TITLE
Always use camelCase for javascript. 

### ISSUE THREAD

**Issue by redoy11** [emtioushossain/Calculator-ReactJs#5]
https://github.com/emtioushossain/Calculator-ReactJs/blob/2730214d86ac062c03ff9098ddd5dd2787343111/src/component/display.js#L25

snake_case is for python. For javascript, please use camelCase and for css, use class-name or visi t the link: https://www.freecodecamp.org/news/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849/

**Comment by emtioushossain** [comment]
Dear redoy11 ,
Thanks for your suggestion , i have added & pushed modified code .
